services:
  jobportal-db:
    image: postgres:16.3-bullseye
    container_name: jobportal-db
    ports:
      - 4443:5432
    environment:
      POSTGRES_PASSWORD: panin@2025
      POSTGRES_USER: panin
      POSTGRES_DB: jobportal_db
    volumes:
      - /Users/citu/Documents/Docker/jobportal-data:/var/lib/postgresql/data
    # networks:
    #   - jobportal-net
  
# networks:
#   jobportal-net:
#     driver: bridge

# jobportal-api:
#   image: "jobportal-api"
#   container_name: jobportal-api
#   ports:
#     - 8000:8080
#   volumes:
#     - /Users/citu/Documents/ITO_Panin/spring/Files/jobportal-files/:/file-server/
#   networks:
#     - jobportal-net